version: '3'

services:
  postgres:
    restart: always
    image: postgres:14.0
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data 
  
  app:
    build: ./
    command: ./main
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: test
      PORT: ":8080"
    ports:
      - "8080:8080"
    depends_on: 
      - postgres
