version: '3'

services:
  postgres:
    restart: always
    image: postgres:16.0
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5436
    volumes:
      - /e/Postgresql/data:/var/lib/postgresql/data 
  
  app:
    build: ./
    command: ./main
    environment:
      DB_HOST: postgres
      DB_PORT: 5436
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: productdb
      PORT: 8080
    ports:
      - 8080:8080
    depends_on: 
      - postgres
